// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Error interface {
	IsError()
}

type TestResult interface {
	IsTestResult()
}

type TestsResult interface {
	IsTestsResult()
}

type G struct {
	A int `json:"a"`
}

type InternalServerError struct {
	Message string `json:"message"`
}

func (InternalServerError) IsError()       {}
func (InternalServerError) IsTestResult()  {}
func (InternalServerError) IsTestsResult() {}

type Tests struct {
	Items []*Test `json:"items"`
}

func (Tests) IsTestsResult() {}
